type User @table {
  displayName: String!
  email: String!
  createdAt: Timestamp!
  photoUrl: String
  phoneNumber: String
  address: String
}

type Restaurant @table {
  owner: User!
  name: String!
  address: String!
  cuisineType: String!
  createdAt: Timestamp!
  description: String
  phoneNumber: String
  imageUrl: String
  openingHours: String
}

type MenuItem @table {
  restaurant: Restaurant!
  name: String!
  price: Float!
  createdAt: Timestamp!
  description: String
  imageUrl: String
  isAvailable: Boolean
}

type Order @table {
  customer: User!
  restaurant: Restaurant!
  driver: User
  orderDate: Timestamp!
  totalAmount: Float!
  status: String!
  deliveryAddress: String!
  deliveryInstructions: String
  notes: String
}

type OrderItem @table(key: ["order", "menuItem"]) {
  order: Order!
  menuItem: MenuItem!
  quantity: Int!
  priceAtTimeOfOrder: Float!
}